import "./globals.css";

export const metadata = {
  title: "Docs App",
  description: "Generated by code with stella",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
